pipeline{
    agent any
   
    stages{
   
        stage('Compile Stage'){
            steps{
               
                    sh '''
          cd demo2-master
      cd demo1
          mvn clean install
    '''
            }
        }   
    }
}
         
    
